language: python
python:
    - "3.6.1"
install:
    - "pip install -r requirements.txt"
    - "pip install coverage"
    - "pip install coveralls"
script:
    - "coverage run --source=tests nosetests tests"
after_success:
    coveralls
